### PR TITLE
KV Value b64 decoder

### PR DESCRIPTION
**Pull request by jmcconnell26**

### CODE REVIEW

**Comment by jmcconnell26** [comment]
For after https://github.com/stusmall/consul-rust/pull/40

**Comment by pierresouchay** [comment]
Hello @jmcconnell26 ... Are you still interested with rebasing this PR? I'll watch it quickly, I promise!

**Comment by jmcconnell26** [comment]
Hi @pierresouchay, that should now be good to go!

**Comment by pierresouchay** [comment]
Hello @jmcconnell26, There are still some conflicts, can you rebase on master?

**Comment by jmcconnell26** [comment]
Hi @pierresouchay, where are you seeing the merge conflicts?
DeepinScreenshot_select-area_20210428180812

**Comment by pierresouchay** [comment]
@jmcconnell26 Well... yes! (Ok, that's weird)
Capture d’écran 2021-04-28 à 19 25 20

**Comment by jmcconnell26** [comment]
Hmmm, interesting
Let me put the changes in a new PR

**Comment by jmcconnell26** [comment]
@pierresouchay, does https://github.com/pierresouchay/consul-rust/pull/55 look any better?

**Comment by pierresouchay** [comment]
@jmcconnell26  Yes! indeed! Might be linked to the change the repository path... Can you close the this PR? Thank You!

**Pull request closed without merging**
